import React, { createContext, useContext, useState } from 'react';

export const LANGUAGES = [
  { code: 'en', name: 'English', native: 'English', state: 'All India', flag: '🇮🇳' },
  { code: 'hi', name: 'Hindi', native: 'हिंदी', state: 'UP, MP, Bihar, Rajasthan, Delhi', flag: '🗺️' },
  { code: 'mr', name: 'Marathi', native: 'मराठी', state: 'Maharashtra', flag: '🗺️' },
  { code: 'gu', name: 'Gujarati', native: 'ગુજરાતી', state: 'Gujarat', flag: '🗺️' },
  { code: 'ta', name: 'Tamil', native: 'தமிழ்', state: 'Tamil Nadu', flag: '🗺️' },
  { code: 'te', name: 'Telugu', native: 'తెలుగు', state: 'Andhra Pradesh, Telangana', flag: '🗺️' },
  { code: 'kn', name: 'Kannada', native: 'ಕನ್ನಡ', state: 'Karnataka', flag: '🗺️' },
  { code: 'ml', name: 'Malayalam', native: 'മലയാളം', state: 'Kerala', flag: '🗺️' },
  { code: 'pa', name: 'Punjabi', native: 'ਪੰਜਾਬੀ', state: 'Punjab, Haryana', flag: '🗺️' },
  { code: 'bn', name: 'Bengali', native: 'বাংলা', state: 'West Bengal', flag: '🗺️' },
  { code: 'or', name: 'Odia', native: 'ଓଡ଼ିଆ', state: 'Odisha', flag: '🗺️' },
  { code: 'as', name: 'Assamese', native: 'অসমীয়া', state: 'Assam', flag: '🗺️' },
  { code: 'ur', name: 'Urdu', native: 'اردو', state: 'J&K, Hyderabad', flag: '🗺️' },
  { code: 'ne', name: 'Nepali', native: 'नेपाली', state: 'Sikkim, Darjeeling', flag: '🗺️' },
  { code: 'kok', name: 'Konkani', native: 'कोंकणी', state: 'Goa', flag: '🗺️' },
  { code: 'sat', name: 'Santali', native: 'ᱥᱟᱱᱛᱟᱲᱤ', state: 'Jharkhand', flag: '🗺️' },
  { code: 'mai', name: 'Maithili', native: 'मैथिली', state: 'Bihar, Jharkhand', flag: '🗺️' },
  { code: 'doi', name: 'Dogri', native: 'डोगरी', state: 'Jammu', flag: '🗺️' },
  { code: 'bho', name: 'Bhojpuri', native: 'भोजपुरी', state: 'UP, Bihar', flag: '🗺️' },
  { code: 'raj', name: 'Rajasthani', native: 'राजस्थानी', state: 'Rajasthan', flag: '🗺️' },
  { code: 'cg', name: 'Chhattisgarhi', native: 'छत्तीसगढ़ी', state: 'Chhattisgarh', flag: '🗺️' },
  { code: 'har', name: 'Haryanvi', native: 'हरियाणवी', state: 'Haryana', flag: '🗺️' },
];

export const TRANSLATIONS = {
  en: {
    // Login
    appName: 'Development Express',
    tagline: 'The Gold Standard of Infrastructure',
    platform: 'Construction Management Platform',
    selectRole: 'SELECT ROLE',
    emailAddress: 'EMAIL ADDRESS',
    password: 'PASSWORD',
    signIn: 'SIGN IN',
    signingIn: 'Signing In...',
    adminRole: 'Admin — Managing Director',
    ownerRole: 'Machine Owner',
    clientRole: 'Client (Contractor)',
    operatorRole: 'Operator',
    since: 'Since 2011 · 15 Years of Excellence',
    // Nav
    dashboard: 'Dashboard',
    myMachines: 'My Machines',
    register: 'Machine Register',
    tracking: 'GPS Tracking',
    reports: 'Reports & Pay',
    alerts: 'Alerts',
    support: 'Support',
    bookMachine: 'Book Machine',
    costCalculator: 'Cost & Booking',
    myBookings: 'My Bookings',
    liveTracking: 'Live Tracking',
    wallet: 'Wallet & Pay',
    overview: 'Overview',
    machines: 'Machines',
    clients: 'Clients',
    owners: 'Owners',
    operators: 'Operators',
    billingWallet: 'Wallet & Billing',
    iot: 'IoT & GPS',
    logout: 'Logout',
    // Common
    active: 'Active',
    idle: 'Idle',
    available: 'Available',
    busy: 'Busy',
    locked: 'Locked',
    live: 'LIVE',
    totalMachines: 'Total Machines',
    activeToday: 'Active Today',
    walletBalance: 'Wallet Balance',
    activeBookings: 'Active Bookings',
    recharge: 'Recharge',
    rechargeWallet: '+ Recharge Wallet',
    payNow: 'Pay Now',
    confirm: 'Confirm',
    cancel: 'Cancel',
    back: 'Go Back',
    download: 'Download',
    submit: 'Submit',
    save: 'Save',
    perHour: 'Per Hour',
    perDay: 'Per Day',
    perWeek: 'Per Week',
    perMonth: 'Per Month',
    advance: 'Advance',
    commission: 'Commission',
    netPayable: 'Net Payable',
    grossBilling: 'Gross Billing',
    bookNow: 'BOOK NOW',
    confirmBooking: 'Confirm Booking',
    cancelBooking: 'Cancel Booking',
    machineStatus: 'Machine Status',
    fuelLevel: 'Fuel Level',
    condition: 'Condition',
    location: 'Location',
    operator: 'Operator',
    experience: 'Experience',
    rating: 'Rating',
    hours: 'Hours',
    days: 'Days',
    weeks: 'Weeks',
    months: 'Months',
    gstInvoice: 'GST Invoice',
    bookingHistory: 'Booking History',
    paymentHistory: 'Payment History',
    noAlerts: 'No Alerts!',
    allMachinesOk: 'All machines running fine.',
    lockMachine: 'Lock Machine',
    machineReg: 'Machine Registration Form',
    ownerInfo: 'Owner Information',
    machineInfo: 'Machine Information',
    pdiInfo: 'PDI Inspection',
    documents: 'Documents Upload',
    agreement: 'Terms & Agreement',
    selectFile: 'Choose File',
    walletOnly: 'WALLET-ONLY · NO CASH ACCEPTED',
    noRefund: 'No Refund Policy',
    cancelPolicy: 'Cancellation Policy',
    whatsapp: 'WhatsApp',
    email: 'Email Support',
    send: 'Send',
    year: 'Year',
    total: 'TOTAL',
    tax: 'Tax',
    status: 'Status',
    type: 'Type',
    date: 'Date',
    machine: 'Machine',
    client: 'Client',
    hmrToday: 'HMR Today',
    hmrTotal: 'Total HMR',
    earnings: 'Earnings',
    amount: 'Amount',
    ref: 'Reference No.',
    fuel: 'Fuel',
    ignition: 'Ignition',
    speed: 'Speed',
    completedBookings: 'Completed Bookings',
    instantCost: 'Instant Cost Calculator',
    baseAmount: 'Base Amount',
    gst18: 'GST (18%)',
    grandTotal: 'Grand Total',
    minimumAdvance: 'MINIMUM ADVANCE REQUIRED',
    selectMachineFirst: 'Please select a machine first',
    viewMachines: '→ View Machines',
    bookingConfirm: 'Confirm Booking',
    walletDeduct: 'Advance will be deducted from Wallet · No Cash · GST Invoice auto-generated',
    noBookings: 'No active bookings',
    goBook: '→ Book a Machine',
    completeBookings: 'Completed Bookings',
    transactions: 'Transaction History',
    customAmount: 'Custom Amount (Min ₹5,000)',
    paymentMethods: 'Payment Methods',
    alertLog: 'Alert Log History',
    sendWhatsapp: 'Send on WhatsApp',
    sendEmail: 'Send Email',
    yourMessage: 'Write your question or issue...',
    importantInfo: 'Important Information for Machine Owners',
    machineDetails: 'Machine & Operator Details',
    liveCamera: '360° Live Camera — Post Booking',
    liveBookAvail: 'Live Feed Available After Booking',
    rateCard: 'Rate Card (Inclusive of Operator)',
    selectBook: 'Book This Machine →',
    selectCalc: '📋 Select & Calculate Cost →',
    bookingType: 'Select Booking Type',
    selectQty: 'Select Quantity',
    walletSufficient: '✅ Proceed',
    walletInsufficient: '❌ Insufficient',
    rechargeFirst: '⚡ Recharge Wallet First',
    cancelWarning: 'Are you sure you want to cancel?',
    noBankRefund: '❌ No Bank Refund — Wallet Credit Only',
    walletCredit: 'Wallet Credit',
    penaltyDeduct: 'Cancellation Penalty (1 hr)',
    blacklistWarning: '⛔ BLACKLIST WARNING',
    directContactProhibited: 'Direct Contact Strictly Prohibited',
    understood: '✅ Understood — Will use Platform',
    lockWarning: 'Machine ignition will be disabled remotely via Teltonika GPS.',
    lockConfirm: '🔒 Confirm Lock',
    allStats: 'Complete Statistics',
    changeLanguage: 'भाषा बदला / Change Language',
  },

  hi: {
    appName: 'डेवलपमेंट एक्सप्रेस',
    tagline: 'बुनियादी ढांचे का स्वर्णिम मानक',
    platform: 'निर्माण प्रबंधन प्लेटफॉर्म',
    selectRole: 'भूमिका चुनें',
    emailAddress: 'ईमेल पता',
    password: 'पासवर्ड',
    signIn: 'साइन इन करें',
    signingIn: 'लॉगिन हो रहा है...',
    adminRole: 'एडमिन — प्रबंध निदेशक',
    ownerRole: 'मशीन मालिक',
    clientRole: 'क्लाइंट (ठेकेदार)',
    operatorRole: 'ऑपरेटर',
    since: '2011 से · 15 वर्षों की उत्कृष्टता',
    dashboard: 'डैशबोर्ड',
    myMachines: 'मेरी मशीनें',
    register: 'मशीन पंजीकरण',
    tracking: 'GPS ट्रैकिंग',
    reports: 'रिपोर्ट और भुगतान',
    alerts: 'अलर्ट',
    support: 'सहायता',
    bookMachine: 'मशीन बुक करें',
    costCalculator: 'लागत कैलकुलेटर',
    myBookings: 'मेरी बुकिंग',
    liveTracking: 'लाइव ट्रैकिंग',
    wallet: 'वॉलेट और भुगतान',
    overview: 'अवलोकन',
    machines: 'मशीनें',
    clients: 'ग्राहक',
    owners: 'मालिक',
    operators: 'ऑपरेटर',
    billingWallet: 'वॉलेट और बिलिंग',
    iot: 'IoT और GPS',
    logout: 'लॉगआउट',
    active: 'सक्रिय',
    idle: 'निष्क्रिय',
    available: 'उपलब्ध',
    busy: 'व्यस्त',
    locked: 'लॉक',
    live: 'लाइव',
    totalMachines: 'कुल मशीनें',
    activeToday: 'आज सक्रिय',
    walletBalance: 'वॉलेट बैलेंस',
    activeBookings: 'सक्रिय बुकिंग',
    recharge: 'रिचार्ज',
    rechargeWallet: '+ वॉलेट रिचार्ज',
    payNow: 'अभी भुगतान करें',
    confirm: 'पुष्टि करें',
    cancel: 'रद्द करें',
    back: 'वापस जाएं',
    download: 'डाउनलोड',
    submit: 'जमा करें',
    save: 'सहेजें',
    perHour: 'प्रति घंटा',
    perDay: 'प्रति दिन',
    perWeek: 'प्रति सप्ताह',
    perMonth: 'प्रति माह',
    advance: 'अग्रिम',
    commission: 'कमीशन',
    netPayable: 'शुद्ध देय',
    grossBilling: 'सकल बिलिंग',
    bookNow: 'अभी बुक करें',
    confirmBooking: 'बुकिंग पुष्टि करें',
    cancelBooking: 'बुकिंग रद्द करें',
    machineStatus: 'मशीन स्थिति',
    fuelLevel: 'ईंधन स्तर',
    condition: 'स्थिति',
    location: 'स्थान',
    operator: 'ऑपरेटर',
    experience: 'अनुभव',
    rating: 'रेटिंग',
    hours: 'घंटे',
    days: 'दिन',
    weeks: 'सप्ताह',
    months: 'महीने',
    gstInvoice: 'GST इनवॉइस',
    bookingHistory: 'बुकिंग इतिहास',
    paymentHistory: 'भुगतान इतिहास',
    noAlerts: 'कोई अलर्ट नहीं!',
    allMachinesOk: 'सभी मशीनें ठीक चल रही हैं।',
    lockMachine: 'मशीन लॉक करें',
    machineReg: 'मशीन पंजीकरण फॉर्म',
    ownerInfo: 'मालिक की जानकारी',
    machineInfo: 'मशीन की जानकारी',
    pdiInfo: 'PDI निरीक्षण',
    documents: 'दस्तावेज़ अपलोड',
    agreement: 'नियम और समझौता',
    selectFile: 'फ़ाइल चुनें',
    walletOnly: 'केवल वॉलेट · नकद स्वीकार नहीं',
    noRefund: 'नो रिफंड नीति',
    cancelPolicy: 'रद्दीकरण नीति',
    whatsapp: 'WhatsApp',
    email: 'ईमेल सहायता',
    send: 'भेजें',
    year: 'वर्ष',
    total: 'कुल',
    tax: 'कर',
    status: 'स्थिति',
    type: 'प्रकार',
    date: 'दिनांक',
    machine: 'मशीन',
    client: 'ग्राहक',
    hmrToday: 'आज का HMR',
    hmrTotal: 'कुल HMR',
    earnings: 'कमाई',
    amount: 'राशि',
    ref: 'संदर्भ संख्या',
    fuel: 'ईंधन',
    ignition: 'इग्निशन',
    speed: 'गति',
    completedBookings: 'पूर्ण बुकिंग',
    instantCost: 'त्वरित लागत कैलकुलेटर',
    baseAmount: 'मूल राशि',
    gst18: 'GST (18%)',
    grandTotal: 'कुल योग',
    minimumAdvance: 'न्यूनतम अग्रिम आवश्यक',
    selectMachineFirst: 'पहले मशीन चुनें',
    viewMachines: '→ मशीनें देखें',
    bookingConfirm: 'बुकिंग पुष्टि करें',
    walletDeduct: 'अग्रिम वॉलेट से काटा जाएगा · नकद नहीं · GST चालान स्वतः बनेगा',
    noBookings: 'कोई सक्रिय बुकिंग नहीं',
    goBook: '→ मशीन बुक करें',
    completeBookings: 'पूर्ण बुकिंग',
    transactions: 'लेनदेन इतिहास',
    customAmount: 'कस्टम राशि (न्यूनतम ₹5,000)',
    paymentMethods: 'भुगतान के तरीके',
    alertLog: 'अलर्ट लॉग',
    sendWhatsapp: 'WhatsApp पर भेजें',
    sendEmail: 'ईमेल भेजें',
    yourMessage: 'अपना प्रश्न या समस्या लिखें...',
    importantInfo: 'मशीन मालिकों के लिए महत्वपूर्ण जानकारी',
    machineDetails: 'मशीन और ऑपरेटर विवरण',
    liveCamera: '360° लाइव कैमरा — बुकिंग के बाद',
    liveBookAvail: 'बुकिंग के बाद लाइव फीड उपलब्ध',
    rateCard: 'दर पत्रक (ऑपरेटर सहित)',
    selectBook: 'यह मशीन बुक करें →',
    selectCalc: '📋 चुनें और लागत देखें →',
    bookingType: 'बुकिंग प्रकार चुनें',
    selectQty: 'मात्रा चुनें',
    walletSufficient: '✅ आगे बढ़ें',
    walletInsufficient: '❌ अपर्याप्त',
    rechargeFirst: '⚡ पहले वॉलेट रिचार्ज करें',
    cancelWarning: 'क्या आप रद्द करना चाहते हैं?',
    noBankRefund: '❌ बैंक रिफंड नहीं — केवल वॉलेट क्रेडिट',
    walletCredit: 'वॉलेट क्रेडिट',
    penaltyDeduct: 'रद्दीकरण दंड (1 घंटा)',
    blacklistWarning: '⛔ ब्लैकलिस्ट चेतावनी',
    directContactProhibited: 'सीधा संपर्क सख्त वर्जित',
    understood: '✅ समझ गया — प्लेटफॉर्म उपयोग करूंगा',
    lockWarning: 'Teltonika GPS के जरिए मशीन का इग्निशन दूर से बंद हो जाएगा।',
    lockConfirm: '🔒 लॉक पुष्टि करें',
    allStats: 'पूर्ण आंकड़े',
    changeLanguage: 'भाषा बदलें',
  },

  mr: {
    appName: 'डेव्हलपमेंट एक्सप्रेस',
    tagline: 'पायाभूत सुविधांचा सुवर्ण दर्जा',
    platform: 'बांधकाम व्यवस्थापन प्लॅटफॉर्म',
    selectRole: 'भूमिका निवडा',
    emailAddress: 'ईमेल पत्ता',
    password: 'पासवर्ड',
    signIn: 'साइन इन करा',
    signingIn: 'लॉगिन होत आहे...',
    adminRole: 'अ‍ॅडमिन — व्यवस्थापकीय संचालक',
    ownerRole: 'मशीन मालक',
    clientRole: 'क्लायंट (कंत्राटदार)',
    operatorRole: 'ऑपरेटर',
    since: '२०११ पासून · १५ वर्षांची उत्कृष्टता',
    dashboard: 'डॅशबोर्ड',
    myMachines: 'माझ्या मशीन',
    register: 'मशीन नोंदणी',
    tracking: 'GPS ट्रॅकिंग',
    reports: 'अहवाल आणि देयक',
    alerts: 'सूचना',
    support: 'मदत',
    bookMachine: 'मशीन बुक करा',
    costCalculator: 'खर्च कॅल्क्युलेटर',
    myBookings: 'माझ्या बुकिंग',
    liveTracking: 'लाइव्ह ट्रॅकिंग',
    wallet: 'वॉलेट आणि देयक',
    overview: 'आढावा',
    machines: 'मशीन्स',
    clients: 'क्लायंट',
    owners: 'मालक',
    operators: 'ऑपरेटर',
    billingWallet: 'वॉलेट आणि बिलिंग',
    iot: 'IoT आणि GPS',
    logout: 'लॉगआउट',
    active: 'कार्यरत',
    idle: 'निष्क्रिय',
    available: 'उपलब्ध',
    busy: 'व्यस्त',
    locked: 'लॉक',
    live: 'लाइव्ह',
    totalMachines: 'एकूण मशीन',
    activeToday: 'आज कार्यरत',
    walletBalance: 'वॉलेट शिल्लक',
    activeBookings: 'सक्रिय बुकिंग',
    recharge: 'रिचार्ज',
    rechargeWallet: '+ वॉलेट रिचार्ज',
    payNow: 'आता पैसे द्या',
    confirm: 'पुष्टी करा',
    cancel: 'रद्द करा',
    back: 'मागे जा',
    download: 'डाउनलोड',
    submit: 'सबमिट करा',
    save: 'जतन करा',
    perHour: 'प्रति तास',
    perDay: 'प्रति दिवस',
    perWeek: 'प्रति आठवडा',
    perMonth: 'प्रति महिना',
    advance: 'अग्रिम',
    commission: 'कमिशन',
    netPayable: 'निव्वळ देय',
    grossBilling: 'एकूण बिलिंग',
    bookNow: 'आत्ता बुक करा',
    confirmBooking: 'बुकिंग पुष्टी करा',
    cancelBooking: 'बुकिंग रद्द करा',
    machineStatus: 'मशीन स्थिती',
    fuelLevel: 'इंधन पातळी',
    condition: 'स्थिती',
    location: 'स्थान',
    operator: 'ऑपरेटर',
    experience: 'अनुभव',
    rating: 'रेटिंग',
    hours: 'तास',
    days: 'दिवस',
    weeks: 'आठवडे',
    months: 'महिने',
    gstInvoice: 'GST बीजक',
    bookingHistory: 'बुकिंग इतिहास',
    paymentHistory: 'देयक इतिहास',
    noAlerts: 'कोणती सूचना नाही!',
    allMachinesOk: 'सर्व मशीन व्यवस्थित चालू आहेत.',
    lockMachine: 'मशीन लॉक करा',
    machineReg: 'मशीन नोंदणी फॉर्म',
    ownerInfo: 'मालकाची माहिती',
    machineInfo: 'मशीनची माहिती',
    pdiInfo: 'PDI तपासणी',
    documents: 'कागदपत्रे अपलोड',
    agreement: 'अटी आणि करार',
    selectFile: 'फाइल निवडा',
    walletOnly: 'फक्त वॉलेट · रोख स्वीकारले जाणार नाही',
    noRefund: 'परतावा नाही नीती',
    cancelPolicy: 'रद्दीकरण नीती',
    whatsapp: 'WhatsApp',
    email: 'ईमेल मदत',
    send: 'पाठवा',
    year: 'वर्ष',
    total: 'एकूण',
    tax: 'कर',
    status: 'स्थिती',
    type: 'प्रकार',
    date: 'तारीख',
    machine: 'मशीन',
    client: 'क्लायंट',
    hmrToday: 'आजचे HMR',
    hmrTotal: 'एकूण HMR',
    earnings: 'कमाई',
    amount: 'रक्कम',
    ref: 'संदर्भ क्रमांक',
    fuel: 'इंधन',
    ignition: 'इग्निशन',
    speed: 'वेग',
    completedBookings: 'पूर्ण बुकिंग',
    instantCost: 'त्वरित खर्च कॅल्क्युलेटर',
    baseAmount: 'मूळ रक्कम',
    gst18: 'GST (१८%)',
    grandTotal: 'एकूण बेरीज',
    minimumAdvance: 'किमान अग्रिम आवश्यक',
    selectMachineFirst: 'आधी मशीन निवडा',
    viewMachines: '→ मशीन बघा',
    bookingConfirm: 'बुकिंग पुष्टी करा',
    walletDeduct: 'अग्रिम वॉलेटमधून वजा होईल · रोख नाही · GST बीजक आपोआप तयार होईल',
    noBookings: 'कोणतीही सक्रिय बुकिंग नाही',
    goBook: '→ मशीन बुक करा',
    completeBookings: 'पूर्ण झालेल्या बुकिंग',
    transactions: 'व्यवहार इतिहास',
    customAmount: 'कस्टम रक्कम (किमान ₹५,०००)',
    paymentMethods: 'देयक पद्धती',
    alertLog: 'अलर्ट लॉग',
    sendWhatsapp: 'WhatsApp वर पाठवा',
    sendEmail: 'ईमेल पाठवा',
    yourMessage: 'तुमचा प्रश्न किंवा अडचण लिहा...',
    importantInfo: 'मशीन मालकांसाठी महत्त्वाची माहिती',
    machineDetails: 'मशीन आणि ऑपरेटर तपशील',
    liveCamera: '३६०° लाइव्ह कॅमेरा — बुकिंगनंतर',
    liveBookAvail: 'बुकिंगनंतर लाइव्ह फीड उपलब्ध',
    rateCard: 'दर पत्रक (ऑपरेटरसह)',
    selectBook: 'ही मशीन बुक करा →',
    selectCalc: '📋 निवडा आणि खर्च बघा →',
    bookingType: 'बुकिंग प्रकार निवडा',
    selectQty: 'प्रमाण निवडा',
    walletSufficient: '✅ पुढे जा',
    walletInsufficient: '❌ अपुरी शिल्लक',
    rechargeFirst: '⚡ आधी वॉलेट रिचार्ज करा',
    cancelWarning: 'तुम्हाला रद्द करायचे आहे का?',
    noBankRefund: '❌ बँक परतावा नाही — फक्त वॉलेट क्रेडिट',
    walletCredit: 'वॉलेट क्रेडिट',
    penaltyDeduct: 'रद्दीकरण दंड (१ तास)',
    blacklistWarning: '⛔ ब्लॅकलिस्ट चेतावणी',
    directContactProhibited: 'थेट संपर्क कठोरपणे निषिद्ध',
    understood: '✅ समजले — प्लॅटफॉर्म वापरेन',
    lockWarning: 'Teltonika GPS द्वारे मशीनचे इग्निशन रिमोटली बंद होईल.',
    lockConfirm: '🔒 लॉक पुष्टी करा',
    allStats: 'संपूर्ण आकडेवारी',
    changeLanguage: 'भाषा बदला',
  },

  gu: {
    appName: 'ડેવલપમેન્ટ એક્સપ્રેસ',
    tagline: 'ઈન્ફ્રાસ્ટ્રક્ચરનો સુવર્ણ ધોરણ',
    platform: 'બાંધકામ વ્યવસ્થાપન પ્લેટફોર્મ',
    selectRole: 'ભૂમિકા પસંદ કરો',
    emailAddress: 'ઈ-મેઈલ સરનામું',
    password: 'પાસવર્ડ',
    signIn: 'સાઈન ઈન કરો',
    signingIn: 'લૉગિન થઈ રહ્યું છે...',
    adminRole: 'એડમિન — મેનેજિંગ ડિરેક્ટર',
    ownerRole: 'મશીન માલિક',
    clientRole: 'ક્લાઈન્ટ (કોન્ટ્રાક્ટર)',
    operatorRole: 'ઓપરેટર',
    since: '2011 થી · 15 વર્ષની શ્રેષ્ઠતા',
    dashboard: 'ડેશબોર્ડ',
    myMachines: 'મારી મશીનો',
    register: 'મશીન નોંધણી',
    tracking: 'GPS ટ્રેકિંગ',
    reports: 'રિપોર્ટ અને ચુકવણી',
    alerts: 'સૂચનાઓ',
    support: 'સહાય',
    bookMachine: 'મશીન બુક કરો',
    costCalculator: 'ખર્ચ કૅલ્ક્યુલેટર',
    myBookings: 'મારી બુકિંગ',
    liveTracking: 'લાઈવ ટ્રેકિંગ',
    wallet: 'વૉલેટ અને ચુકવણી',
    overview: 'ઝાંખી',
    machines: 'મશીનો',
    clients: 'ગ્રાહકો',
    owners: 'માલિકો',
    operators: 'ઓપરેટરો',
    billingWallet: 'વૉલેટ અને બિલિંગ',
    iot: 'IoT અને GPS',
    logout: 'લૉગઆઉટ',
    active: 'સક્રિય',
    idle: 'નિષ્ક્રિય',
    available: 'ઉપલબ્ધ',
    busy: 'વ્યસ્ત',
    locked: 'લૉક',
    live: 'લાઈવ',
    totalMachines: 'કુલ મશીનો',
    activeToday: 'આજે સક્રિય',
    walletBalance: 'વૉલેટ બૅલેન્સ',
    activeBookings: 'સક્રિય બુકિંગ',
    recharge: 'રિચાર્જ',
    rechargeWallet: '+ વૉલેટ રિચાર્જ',
    payNow: 'હવે ચૂકવો',
    confirm: 'પુષ્ટિ કરો',
    cancel: 'રદ કરો',
    back: 'પાછા જાઓ',
    download: 'ડાઉનલોડ',
    submit: 'સબમિટ કરો',
    save: 'સાચવો',
    perHour: 'દર કલાક',
    perDay: 'દરરોજ',
    perWeek: 'દર અઠવાડિયે',
    perMonth: 'દર મહિને',
    advance: 'એડવાન્સ',
    commission: 'કમિશન',
    netPayable: 'ચોખ્ખી ચૂકવણી',
    grossBilling: 'કુલ બિલિંગ',
    bookNow: 'હવે બુક કરો',
    confirmBooking: 'બુકિંગ પુષ્ટિ કરો',
    cancelBooking: 'બુકિંગ રદ કરો',
    machineStatus: 'મશીન સ્થિતિ',
    fuelLevel: 'ઇંધણ સ્તર',
    condition: 'સ્થિતિ',
    location: 'સ્થાન',
    operator: 'ઓપરેટર',
    experience: 'અનુભવ',
    rating: 'રેટિંગ',
    hours: 'કલાક',
    days: 'દિવસ',
    weeks: 'અઠવાડિયા',
    months: 'મહિના',
    gstInvoice: 'GST ઈન્વૉઈસ',
    bookingHistory: 'બુકિંગ ઈતિહાસ',
    paymentHistory: 'ચુકવણી ઈતિહાસ',
    noAlerts: 'કોઈ સૂચના નથી!',
    allMachinesOk: 'બધી મશીનો સારી ચાલે છે.',
    lockMachine: 'મશીન લૉક કરો',
    machineReg: 'મશીન નોંધણી ફોર્મ',
    ownerInfo: 'માલિકની માહિતી',
    machineInfo: 'મશીનની માહિતી',
    pdiInfo: 'PDI તપાસ',
    documents: 'દસ્તાવેજ અપલોડ',
    agreement: 'નિયમો અને કરાર',
    selectFile: 'ફાઈલ પસંદ કરો',
    walletOnly: 'માત્ર વૉલેટ · રોકડ સ્વીકારાશે નહીં',
    noRefund: 'નો રિફન્ડ નીતિ',
    cancelPolicy: 'રદ કરવાની નીતિ',
    whatsapp: 'WhatsApp',
    email: 'ઈ-મેઈલ સહાય',
    send: 'મોકલો',
    year: 'વર્ષ',
    total: 'કુલ',
    tax: 'કર',
    status: 'સ્થિતિ',
    type: 'પ્રકાર',
    date: 'તારીખ',
    machine: 'મશીન',
    client: 'ગ્રાહક',
    hmrToday: 'આજનું HMR',
    hmrTotal: 'કુલ HMR',
    earnings: 'કમાણી',
    amount: 'રકમ',
    ref: 'સંદર્ભ નંબર',
    fuel: 'ઇંધણ',
    ignition: 'ઇગ્નિશન',
    speed: 'ઝડપ',
    completedBookings: 'પૂર્ણ બુકિંગ',
    instantCost: 'તાત્કાલિક ખર્ચ કૅલ્ક્યુલેટર',
    baseAmount: 'મૂળ રકમ',
    gst18: 'GST (18%)',
    grandTotal: 'કુલ સરવાળો',
    minimumAdvance: 'ઓછામાં ઓછો એડવાન્સ જરૂરી',
    selectMachineFirst: 'પહેલા મશીન પસંદ કરો',
    viewMachines: '→ મશીન જુઓ',
    bookingConfirm: 'બુકિંગ પુષ્ટિ કરો',
    walletDeduct: 'એડવાન્સ વૉલેટથી કપાશે · રોકડ નહીં · GST ઈન્વૉઈસ આપોઆપ બનશે',
    noBookings: 'કોઈ સક્રિય બુકિંગ નથી',
    goBook: '→ મશીન બુક કરો',
    completeBookings: 'પૂર્ણ બુકિંગ',
    transactions: 'વ્યવહાર ઈતિહાસ',
    customAmount: 'કસ્ટમ રકમ (ઓછામાં ઓછી ₹5,000)',
    paymentMethods: 'ચુકવણી પદ્ધતિ',
    alertLog: 'અલર્ટ લૉગ',
    sendWhatsapp: 'WhatsApp પર મોકલો',
    sendEmail: 'ઈ-મેઈલ મોકલો',
    yourMessage: 'તમારો પ્રશ્ન અથવા સમસ્યા લખો...',
    importantInfo: 'મશીન માલિકો માટે મહત્વની માહિતી',
    machineDetails: 'મશીન અને ઓપરેટર વિગતો',
    liveCamera: '360° લાઈવ કૅમેરા — બુકિંગ પછી',
    liveBookAvail: 'બુકિંગ પછી લાઈવ ફીડ ઉપલ',
    rateCard: 'દર કાર્ડ (ઓપરેટર સહિત)',
    selectBook: 'આ મશીન બુક કરો →',
    selectCalc: '📋 પસંદ કરો અને ખર્ચ જુઓ →',
    bookingType: 'બુકિંગ પ્રકાર પસંદ કરો',
    selectQty: 'જથ્થો પસંદ કરો',
    walletSufficient: '✅ આગળ વધો',
    walletInsufficient: '❌ અપૂરતું',
    rechargeFirst: '⚡ પહેલા વૉલેટ રિચાર્જ કરો',
    cancelWarning: 'શું તમે રદ કરવા ઈચ્છો છો?',
    noBankRefund: '❌ બૅન્ક રિફન્ડ નહીં — માત્ર વૉલેટ ક્રેડિટ',
    walletCredit: 'વૉલેટ ક્રેડિટ',
    penaltyDeduct: 'રદ કરવાનો દંડ (1 કલાક)',
    blacklistWarning: '⛔ બ્લૅકલિસ્ટ ચેતવણી',
    directContactProhibited: 'સીધો સંપર્ક સખ્ત પ્રતિબંધિત',
    understood: '✅ સમજ્યો — પ્લેટફોર્મ વાપરીશ',
    lockWarning: 'Teltonika GPS દ્વારા મશીનનું ઈગ્નિશન દૂરથી બંધ થઈ જશે.',
    lockConfirm: '🔒 લૉક પુષ્ટિ કરો',
    allStats: 'સંપૂર્ણ આંકડા',
    changeLanguage: 'ભાષા બદલો',
  },

  ta: {
    appName: 'டெவலப்மென்ட் எக்ஸ்பிரஸ்',
    tagline: 'உள்கட்டமைப்பின் தங்க தரம்',
    platform: 'கட்டுமான மேலாண்மை தளம்',
    selectRole: 'பங்கு தேர்வு செய்யுங்கள்',
    emailAddress: 'மின்னஞ்சல் முகவரி',
    password: 'கடவுச்சொல்',
    signIn: 'உள்நுழைக',
    signingIn: 'உள்நுழைகிறது...',
    adminRole: 'நிர்வாகி — மேலாண்மை இயக்குனர்',
    ownerRole: 'இயந்திர உரிமையாளர்',
    clientRole: 'வாடிக்கையாளர் (ஒப்பந்தக்காரர்)',
    operatorRole: 'ஆபரேட்டர்',
    since: '2011 முதல் · 15 ஆண்டுகள் சிறந்து',
    dashboard: 'டாஷ்போர்டு',
    myMachines: 'என் இயந்திரங்கள்',
    register: 'இயந்திர பதிவு',
    tracking: 'GPS கண்காணிப்பு',
    reports: 'அறிக்கைகள் & கட்டணம்',
    alerts: 'எச்சரிக்கைகள்',
    support: 'ஆதரவு',
    bookMachine: 'இயந்திரம் முன்பதிவு',
    costCalculator: 'செலவு கணக்கீடு',
    myBookings: 'என் முன்பதிவுகள்',
    liveTracking: 'நேரடி கண்காணிப்பு',
    wallet: 'வாலட் & கட்டணம்',
    overview: 'கண்ணோட்டம்',
    machines: 'இயந்திரங்கள்',
    clients: 'வாடிக்கையாளர்கள்',
    owners: 'உரிமையாளர்கள்',
    operators: 'ஆபரேட்டர்கள்',
    billingWallet: 'வாலட் & பில்லிங்',
    iot: 'IoT & GPS',
    logout: 'வெளியேறு',
    active: 'செயலில்',
    idle: 'செயலற்று',
    available: 'கிடைக்கிறது',
    busy: 'பிஸி',
    locked: 'பூட்டப்பட்டது',
    live: 'நேரடி',
    totalMachines: 'மொத்த இயந்திரங்கள்',
    activeToday: 'இன்று செயலில்',
    walletBalance: 'வாலட் இருப்பு',
    activeBookings: 'செயலில் உள்ள முன்பதிவுகள்',
    recharge: 'ரீசார்ஜ்',
    rechargeWallet: '+ வாலட் ரீசார்ஜ்',
    payNow: 'இப்போது செலுத்துங்கள்',
    confirm: 'உறுதிப்படுத்துங்கள்',
    cancel: 'ரத்து செய்யுங்கள்',
    back: 'திரும்பு',
    download: 'பதிவிறக்கம்',
    submit: 'சமர்ப்பிக்கவும்',
    save: 'சேமிக்கவும்',
    perHour: 'மணிக்கு',
    perDay: 'நாளுக்கு',
    perWeek: 'வாரத்திற்கு',
    perMonth: 'மாதத்திற்கு',
    advance: 'முன்பணம்',
    commission: 'கமிஷன்',
    netPayable: 'நிகர செலுத்த வேண்டியது',
    grossBilling: 'மொத்த பில்லிங்',
    bookNow: 'இப்போது பதிவு செய்யுங்கள்',
    confirmBooking: 'முன்பதிவு உறுதிப்படுத்துங்கள்',
    cancelBooking: 'முன்பதிவு ரத்து செய்யுங்கள்',
    machineStatus: 'இயந்திர நிலை',
    fuelLevel: 'எரிபொருள் அளவு',
    condition: 'நிலை',
    location: 'இடம்',
    operator: 'ஆபரேட்டர்',
    experience: 'அனுபவம்',
    rating: 'மதிப்பீடு',
    hours: 'மணிநேரம்',
    days: 'நாட்கள்',
    weeks: 'வாரங்கள்',
    months: 'மாதங்கள்',
    gstInvoice: 'GST இன்வாய்ஸ்',
    bookingHistory: 'முன்பதிவு வரலாறு',
    paymentHistory: 'கட்டண வரலாறு',
    noAlerts: 'எச்சரிக்கை இல்லை!',
    allMachinesOk: 'அனைத்து இயந்திரங்களும் சரியாக இயங்குகின்றன.',
    lockMachine: 'இயந்திரத்தை பூட்டுங்கள்',
    machineReg: 'இயந்திர பதிவு படிவம்',
    ownerInfo: 'உரிமையாளர் தகவல்',
    machineInfo: 'இயந்திர தகவல்',
    pdiInfo: 'PDI ஆய்வு',
    documents: 'ஆவணங்கள் பதிவேற்றம்',
    agreement: 'விதிமுறைகள் & ஒப்பந்தம்',
    selectFile: 'கோப்பை தேர்வு செய்யுங்கள்',
    walletOnly: 'வாலட் மட்டுமே · பணம் ஏற்கப்படாது',
    noRefund: 'திரும்ப செலுத்த மாட்டோம்',
    cancelPolicy: 'ரத்து கொள்கை',
    whatsapp: 'WhatsApp',
    email: 'மின்னஞ்சல் ஆதரவு',
    send: 'அனுப்புங்கள்',
    year: 'ஆண்டு',
    total: 'மொத்தம்',
    tax: 'வரி',
    status: 'நிலை',
    type: 'வகை',
    date: 'தேதி',
    machine: 'இயந்திரம்',
    client: 'வாடிக்கையாளர்',
    hmrToday: 'இன்றைய HMR',
    hmrTotal: 'மொத்த HMR',
    earnings: 'வருமானம்',
    amount: 'தொகை',
    ref: 'குறிப்பு எண்',
    fuel: 'எரிபொருள்',
    ignition: 'இக்னிஷன்',
    speed: 'வேகம்',
    completedBookings: 'முடிந்த முன்பதிவுகள்',
    instantCost: 'உடனடி செலவு கணக்கீடு',
    baseAmount: 'அடிப்படை தொகை',
    gst18: 'GST (18%)',
    grandTotal: 'மொத்த தொகை',
    minimumAdvance: 'குறைந்தபட்ச முன்பணம் தேவை',
    selectMachineFirst: 'முதலில் இயந்திரம் தேர்வு செய்யுங்கள்',
    viewMachines: '→ இயந்திரங்களை பாருங்கள்',
    bookingConfirm: 'முன்பதிவு உறுதிப்படுத்துங்கள்',
    walletDeduct: 'முன்பணம் வாலட்டிலிருந்து கழிக்கப்படும் · பணம் இல்லை · GST தானாக உருவாகும்',
    noBookings: 'செயலில் உள்ள முன்பதிவுகள் இல்லை',
    goBook: '→ இயந்திரம் பதிவு செய்யுங்கள்',
    completeBookings: 'முடிந்த முன்பதிவுகள்',
    transactions: 'பரிவர்த்தனை வரலாறு',
    customAmount: 'தனிப்பயன் தொகை (குறைந்தது ₹5,000)',
    paymentMethods: 'கட்டண முறைகள்',
    alertLog: 'எச்சரிக்கை பதிவு',
    sendWhatsapp: 'WhatsApp-ல் அனுப்புங்கள்',
    sendEmail: 'மின்னஞ்சல் அனுப்புங்கள்',
    yourMessage: 'உங்கள் கேள்வி அல்லது பிரச்சனை எழுதுங்கள்...',
    importantInfo: 'இயந்திர உரிமையாளர்களுக்கு முக்கியமான தகவல்',
    machineDetails: 'இயந்திரம் & ஆபரேட்டர் விவரங்கள்',
    liveCamera: '360° நேரடி கேமரா — பதிவிற்கு பின்',
    liveBookAvail: 'பதிவிற்கு பின் நேரடி ஃபீட் கிடைக்கும்',
    rateCard: 'கட்டண அட்டை (ஆபரேட்டர் உட்பட)',
    selectBook: 'இந்த இயந்திரத்தை பதிவு செய்யுங்கள் →',
    selectCalc: '📋 தேர்வு செய்து செலவு பாருங்கள் →',
    bookingType: 'முன்பதிவு வகை தேர்வு செய்யுங்கள்',
    selectQty: 'அளவு தேர்வு செய்யுங்கள்',
    walletSufficient: '✅ தொடரலாம்',
    walletInsufficient: '❌ போதுமான இல்லை',
    rechargeFirst: '⚡ முதலில் வாலட் ரீசார்ஜ் செய்யுங்கள்',
    cancelWarning: 'நீங்கள் ரத்து செய்ய விரும்புகிறீர்களா?',
    noBankRefund: '❌ வங்கி திரும்ப இல்லை — வாலட் கிரெடிட் மட்டுமே',
    walletCredit: 'வாலட் கிரெடிட்',
    penaltyDeduct: 'ரத்து அபராதம் (1 மணி)',
    blacklistWarning: '⛔ பிளாக்லிஸ்ட் எச்சரிக்கை',
    directContactProhibited: 'நேரடி தொடர்பு கண்டிப்பாக தடை',
    understood: '✅ புரிந்தது — தளத்தை பயன்படுத்துவேன்',
    lockWarning: 'Teltonika GPS மூலம் இயந்திரத்தின் இக்னிஷன் தொலைவிலிருந்து முடக்கப்படும்.',
    lockConfirm: '🔒 பூட்டு உறுதிப்படுத்துங்கள்',
    allStats: 'முழுமையான புள்ளிவிவரங்கள்',
    changeLanguage: 'மொழி மாற்றுங்கள்',
  },

  te: {
    appName: 'డెవలప్‌మెంట్ ఎక్స్‌ప్రెస్',
    tagline: 'మౌలిక సదుపాయాల స్వర్ణ ప్రమాణం',
    platform: 'నిర్మాణ నిర్వహణ వేదిక',
    selectRole: 'పాత్రను ఎంచుకోండి',
    emailAddress: 'ఇమెయిల్ చిరునామా',
    password: 'పాస్‌వర్డ్',
    signIn: 'సైన్ ఇన్ చేయండి',
    signingIn: 'లాగిన్ అవుతోంది...',
    adminRole: 'అడ్మిన్ — మేనేజింగ్ డైరెక్టర్',
    ownerRole: 'మెషీన్ యజమాని',
    clientRole: 'క్లయంట్ (కాంట్రాక్టర్)',
    operatorRole: 'ఆపరేటర్',
    since: '2011 నుండి · 15 సంవత్సరాల శ్రేష్ఠత',
    dashboard: 'డాష్‌బోర్డ్',
    myMachines: 'నా మెషీన్‌లు',
    register: 'మెషీన్ నమోదు',
    tracking: 'GPS ట్రాకింగ్',
    reports: 'నివేదికలు & చెల్లింపు',
    alerts: 'హెచ్చరికలు',
    support: 'మద్దతు',
    bookMachine: 'మెషీన్ బుక్ చేయండి',
    costCalculator: 'ఖర్చు కాలిక్యులేటర్',
    myBookings: 'నా బుకింగ్‌లు',
    liveTracking: 'లైవ్ ట్రాకింగ్',
    wallet: 'వాలెట్ & చెల్లింపు',
    overview: 'అవలోకనం',
    machines: 'మెషీన్‌లు',
    clients: 'క్లయంట్‌లు',
    owners: 'యజమానులు',
    operators: 'ఆపరేటర్‌లు',
    billingWallet: 'వాలెట్ & బిల్లింగ్',
    iot: 'IoT & GPS',
    logout: 'లాగ్అవుట్',
    active: 'చురుకైన',
    idle: 'నిష్క్రియ',
    available: 'అందుబాటులో',
    busy: 'బిజీ',
    locked: 'లాక్ చేయబడింది',
    live: 'లైవ్',
    totalMachines: 'మొత్తం మెషీన్‌లు',
    activeToday: 'నేడు చురుకైన',
    walletBalance: 'వాలెట్ బ్యాలెన్స్',
    activeBookings: 'చురుకైన బుకింగ్‌లు',
    recharge: 'రీఛార్జ్',
    rechargeWallet: '+ వాలెట్ రీఛార్జ్',
    payNow: 'ఇప్పుడు చెల్లించండి',
    confirm: 'నిర్ధారించండి',
    cancel: 'రద్దు చేయండి',
    back: 'వెనుకకు',
    download: 'డౌన్లోడ్',
    submit: 'సమర్పించండి',
    save: 'సేవ్ చేయండి',
    perHour: 'గంటకు',
    perDay: 'రోజుకు',
    perWeek: 'వారానికి',
    perMonth: 'నెలకు',
    advance: 'అడ్వాన్స్',
    commission: 'కమీషన్',
    netPayable: 'నికర చెల్లించవలసిన',
    grossBilling: 'స్థూల బిల్లింగ్',
    bookNow: 'ఇప్పుడే బుక్ చేయండి',
    confirmBooking: 'బుకింగ్ నిర్ధారించండి',
    cancelBooking: 'బుకింగ్ రద్దు చేయండి',
    machineStatus: 'మెషీన్ స్థితి',
    fuelLevel: 'ఇంధన స్థాయి',
    condition: 'స్థితి',
    location: 'స్థానం',
    operator: 'ఆపరేటర్',
    experience: 'అనుభవం',
    rating: 'రేటింగ్',
    hours: 'గంటలు',
    days: 'రోజులు',
    weeks: 'వారాలు',
    months: 'నెలలు',
    gstInvoice: 'GST ఇన్వాయిస్',
    bookingHistory: 'బుకింగ్ చరిత్ర',
    paymentHistory: 'చెల్లింపు చరిత్ర',
    noAlerts: 'హెచ్చరికలు లేవు!',
    allMachinesOk: 'అన్ని మెషీన్‌లు సరిగ్గా పని చేస్తున్నాయి.',
    lockMachine: 'మెషీన్ లాక్ చేయండి',
    machineReg: 'మెషీన్ నమోదు ఫారం',
    ownerInfo: 'యజమాని సమాచారం',
    machineInfo: 'మెషీన్ సమాచారం',
    pdiInfo: 'PDI తనిఖీ',
    documents: 'పత్రాలు అప్‌లోడ్',
    agreement: 'నిబంధనలు & ఒప్పందం',
    selectFile: 'ఫైల్ ఎంచుకోండి',
    walletOnly: 'వాలెట్ మాత్రమే · నగదు అంగీకరించబడదు',
    noRefund: 'రీఫండ్ లేదు విధానం',
    cancelPolicy: 'రద్దు విధానం',
    whatsapp: 'WhatsApp',
    email: 'ఇమెయిల్ మద్దతు',
    send: 'పంపండి',
    year: 'సంవత్సరం',
    total: 'మొత్తం',
    tax: 'పన్ను',
    status: 'స్థితి',
    type: 'రకం',
    date: 'తేదీ',
    machine: 'మెషీన్',
    client: 'క్లయంట్',
    hmrToday: 'నేటి HMR',
    hmrTotal: 'మొత్తం HMR',
    earnings: 'ఆదాయం',
    amount: 'మొత్తం',
    ref: 'రెఫరెన్స్ నంబర్',
    fuel: 'ఇంధనం',
    ignition: 'ఇగ్నిషన్',
    speed: 'వేగం',
    completedBookings: 'పూర్తయిన బుకింగ్‌లు',
    instantCost: 'తక్షణ ఖర్చు కాలిక్యులేటర్',
    baseAmount: 'ప్రాథమిక మొత్తం',
    gst18: 'GST (18%)',
    grandTotal: 'మొత్తం మొత్తం',
    minimumAdvance: 'కనీస అడ్వాన్స్ అవసరం',
    selectMachineFirst: 'ముందు మెషీన్ ఎంచుకోండి',
    viewMachines: '→ మెషీన్‌లు చూడండి',
    bookingConfirm: 'బుకింగ్ నిర్ధారించండి',
    walletDeduct: 'అడ్వాన్స్ వాలెట్ నుండి తీసివేయబడుతుంది · నగదు లేదు · GST స్వయంచాలకంగా రూపొందుతుంది',
    noBookings: 'చురుకైన బుకింగ్‌లు లేవు',
    goBook: '→ మెషీన్ బుక్ చేయండి',
    completeBookings: 'పూర్తయిన బుకింగ్‌లు',
    transactions: 'లావాదేవీ చరిత్ర',
    customAmount: 'కస్టమ్ మొత్తం (కనీసం ₹5,000)',
    paymentMethods: 'చెల్లింపు పద్ధతులు',
    alertLog: 'హెచ్చరిక లాగ్',
    sendWhatsapp: 'WhatsApp లో పంపండి',
    sendEmail: 'ఇమెయిల్ పంపండి',
    yourMessage: 'మీ ప్రశ్న లేదా సమస్య రాయండి...',
    importantInfo: 'మెషీన్ యజమానులకు ముఖ్యమైన సమాచారం',
    machineDetails: 'మెషీన్ & ఆపరేటర్ వివరాలు',
    liveCamera: '360° లైవ్ కెమెరా — బుకింగ్ తర్వాత',
    liveBookAvail: 'బుకింగ్ తర్వాత లైవ్ ఫీడ్ అందుబాటులో',
    rateCard: 'రేట్ కార్డ్ (ఆపరేటర్ సహా)',
    selectBook: 'ఈ మెషీన్ బుక్ చేయండి →',
    selectCalc: '📋 ఎంచుకోండి & ఖర్చు చూడండి →',
    bookingType: 'బుకింగ్ రకం ఎంచుకోండి',
    selectQty: 'పరిమాణం ఎంచుకోండి',
    walletSufficient: '✅ కొనసాగండి',
    walletInsufficient: '❌ సరిపోదు',
    rechargeFirst: '⚡ ముందు వాలెట్ రీఛార్జ్ చేయండి',
    cancelWarning: 'మీరు రద్దు చేయాలనుకుంటున్నారా?',
    noBankRefund: '❌ బ్యాంక్ రీఫండ్ లేదు — వాలెట్ క్రెడిట్ మాత్రమే',
    walletCredit: 'వాలెట్ క్రెడిట్',
    penaltyDeduct: 'రద్దు జరిమానా (1 గంట)',
    blacklistWarning: '⛔ బ్లాక్‌లిస్ట్ హెచ్చరిక',
    directContactProhibited: 'ప్రత్యక్ష సంప్రదింపులు కఠినంగా నిషేధించబడ్డాయి',
    understood: '✅ అర్థమైంది — వేదికను ఉపయోగిస్తాను',
    lockWarning: 'Teltonika GPS ద్వారా మెషీన్ ఇగ్నిషన్ దూరంగా నిలిపివేయబడుతుంది.',
    lockConfirm: '🔒 లాక్ నిర్ధారించండి',
    allStats: 'పూర్తి గణాంకాలు',
    changeLanguage: 'భాషను మార్చండి',
  },

  kn: {
    appName: 'ಡೆವಲಪ್‌ಮೆಂಟ್ ಎಕ್ಸ್‌ಪ್ರೆಸ್',
    tagline: 'ಮೂಲಸೌಕರ್ಯದ ಚಿನ್ನದ ಮಾನದಂಡ',
    platform: 'ನಿರ್ಮಾಣ ನಿರ್ವಹಣಾ ವೇದಿಕೆ',
    selectRole: 'ಪಾತ್ರ ಆಯ್ಕೆ ಮಾಡಿ',
    emailAddress: 'ಇಮೇಲ್ ವಿಳಾಸ',
    password: 'ಪಾಸ್‌ವರ್ಡ್',
    signIn: 'ಸೈನ್ ಇನ್ ಮಾಡಿ',
    signingIn: 'ಲಾಗಿನ್ ಆಗುತ್ತಿದೆ...',
    adminRole: 'ಅಡ್ಮಿನ್ — ವ್ಯವಸ್ಥಾಪಕ ನಿರ್ದೇಶಕ',
    ownerRole: 'ಯಂತ್ರ ಮಾಲೀಕ',
    clientRole: 'ಕ್ಲೈಂಟ್ (ಗುತ್ತಿಗೆದಾರ)',
    operatorRole: 'ಆಪರೇಟರ್',
    since: '2011 ರಿಂದ · 15 ವರ್ಷಗಳ ಶ್ರೇಷ್ಠತೆ',
    dashboard: 'ಡ್ಯಾಶ್‌ಬೋರ್ಡ್',
    myMachines: 'ನನ್ನ ಯಂತ್ರಗಳು',
    register: 'ಯಂತ್ರ ನೋಂದಣಿ',
    tracking: 'GPS ಟ್ರ್ಯಾಕಿಂಗ್',
    reports: 'ವರದಿಗಳು & ಪಾವತಿ',
    alerts: 'ಎಚ್ಚರಿಕೆಗಳು',
    support: 'ಬೆಂಬಲ',
    bookMachine: 'ಯಂತ್ರ ಬುಕ್ ಮಾಡಿ',
    costCalculator: 'ವೆಚ್ಚ ಕ್ಯಾಲ್ಕುಲೇಟರ್',
    myBookings: 'ನನ್ನ ಬುಕಿಂಗ್‌ಗಳು',
    liveTracking: 'ಲೈವ್ ಟ್ರ್ಯಾಕಿಂಗ್',
    wallet: 'ವಾಲೆಟ್ & ಪಾವತಿ',
    overview: 'ಅವಲೋಕನ',
    machines: 'ಯಂತ್ರಗಳು',
    clients: 'ಗ್ರಾಹಕರು',
    owners: 'ಮಾಲೀಕರು',
    operators: 'ಆಪರೇಟರ್‌ಗಳು',
    billingWallet: 'ವಾಲೆಟ್ & ಬಿಲ್ಲಿಂಗ್',
    iot: 'IoT & GPS',
    logout: 'ಲಾಗ್ ಔಟ್',
    active: 'ಸಕ್ರಿಯ',
    idle: 'ನಿಷ್ಕ್ರಿಯ',
    available: 'ಲಭ್ಯ',
    busy: 'ಬ್ಯುಸಿ',
    locked: 'ಲಾಕ್',
    live: 'ಲೈವ್',
    totalMachines: 'ಒಟ್ಟು ಯಂತ್ರಗಳು',
    activeToday: 'ಇಂದು ಸಕ್ರಿಯ',
    walletBalance: 'ವಾಲೆಟ್ ಬ್ಯಾಲೆನ್ಸ್',
    activeBookings: 'ಸಕ್ರಿಯ ಬುಕಿಂಗ್‌ಗಳು',
    recharge: 'ರೀಚಾರ್ಜ್',
    rechargeWallet: '+ ವಾಲೆಟ್ ರೀಚಾರ್ಜ್',
    payNow: 'ಈಗ ಪಾವತಿಸಿ',
    confirm: 'ದೃಢೀಕರಿಸಿ',
    cancel: 'ರದ್ದು ಮಾಡಿ',
    back: 'ಹಿಂದೆ ಹೋಗಿ',
    download: 'ಡೌನ್‌ಲೋಡ್',
    submit: 'ಸಲ್ಲಿಸಿ',
    save: 'ಉಳಿಸಿ',
    perHour: 'ಗಂಟೆಗೆ',
    perDay: 'ದಿನಕ್ಕೆ',
    perWeek: 'ವಾರಕ್ಕೆ',
    perMonth: 'ತಿಂಗಳಿಗೆ',
    advance: 'ಮುಂಗಡ',
    commission: 'ಕಮಿಷನ್',
    netPayable: 'ನಿವ್ವಳ ಪಾವತಿಸಬೇಕಾದ',
    grossBilling: 'ಒಟ್ಟು ಬಿಲ್ಲಿಂಗ್',
    bookNow: 'ಈಗ ಬುಕ್ ಮಾಡಿ',
    confirmBooking: 'ಬುಕಿಂಗ್ ದೃಢೀಕರಿಸಿ',
    cancelBooking: 'ಬುಕಿಂಗ್ ರದ್ದು ಮಾಡಿ',
    machineStatus: 'ಯಂತ್ರ ಸ್ಥಿತಿ',
    fuelLevel: 'ಇಂಧನ ಮಟ್ಟ',
    condition: 'ಸ್ಥಿತಿ',
    location: 'ಸ್ಥಳ',
    operator: 'ಆಪರೇಟರ್',
    experience: 'ಅನುಭವ',
    rating: 'ರೇಟಿಂಗ್',
    hours: 'ಗಂಟೆಗಳು',
    days: 'ದಿನಗಳು',
    weeks: 'ವಾರಗಳು',
    months: 'ತಿಂಗಳುಗಳು',
    gstInvoice: 'GST ಇನ್‌ವಾಯ್ಸ್',
    bookingHistory: 'ಬುಕಿಂಗ್ ಇತಿಹಾಸ',
    paymentHistory: 'ಪಾವತಿ ಇತಿಹಾಸ',
    noAlerts: 'ಯಾವುದೇ ಎಚ್ಚರಿಕೆಗಳಿಲ್ಲ!',
    allMachinesOk: 'ಎಲ್ಲಾ ಯಂತ್ರಗಳು ಸರಿಯಾಗಿ ಕಾರ್ಯನಿರ್ವಹಿಸುತ್ತಿವೆ.',
    lockMachine: 'ಯಂತ್ರ ಲಾಕ್ ಮಾಡಿ',
    machineReg: 'ಯಂತ್ರ ನೋಂದಣಿ ಫಾರ್ಮ್',
    ownerInfo: 'ಮಾಲೀಕ ಮಾಹಿತಿ',
    machineInfo: 'ಯಂತ್ರ ಮಾಹಿತಿ',
    pdiInfo: 'PDI ತಪಾಸಣೆ',
    documents: 'ದಾಖಲೆಗಳು ಅಪ್‌ಲೋಡ್',
    agreement: 'ನಿಯಮಗಳು & ಒಪ್ಪಂದ',
    selectFile: 'ಫೈಲ್ ಆಯ್ಕೆ ಮಾಡಿ',
    walletOnly: 'ವಾಲೆಟ್ ಮಾತ್ರ · ನಗದು ಸ್ವೀಕರಿಸಲಾಗದು',
    noRefund: 'ರಿಫಂಡ್ ಇಲ್ಲ ನೀತಿ',
    cancelPolicy: 'ರದ್ದು ನೀತಿ',
    whatsapp: 'WhatsApp',
    email: 'ಇಮೇಲ್ ಬೆಂಬಲ',
    send: 'ಕಳುಹಿಸಿ',
    year: 'ವರ್ಷ', total: 'ಒಟ್ಟು', tax: 'ತೆರಿಗೆ', status: 'ಸ್ಥಿತಿ',
    type: 'ವಿಧ', date: 'ದಿನಾಂಕ', machine: 'ಯಂತ್ರ', client: 'ಗ್ರಾಹಕ',
    hmrToday: 'ಇಂದಿನ HMR', hmrTotal: 'ಒಟ್ಟು HMR', earnings: 'ಆದಾಯ',
    amount: 'ಮೊತ್ತ', ref: 'ಉಲ್ಲೇಖ ಸಂಖ್ಯೆ', fuel: 'ಇಂಧನ', ignition: 'ಇಗ್ನಿಷನ್',
    speed: 'ವೇಗ', completedBookings: 'ಪೂರ್ಣ ಬುಕಿಂಗ್‌ಗಳು',
    instantCost: 'ತಕ್ಷಣದ ವೆಚ್ಚ ಕ್ಯಾಲ್ಕುಲೇಟರ್', baseAmount: 'ಮೂಲ ಮೊತ್ತ',
    gst18: 'GST (18%)', grandTotal: 'ಒಟ್ಟು ಮೊತ್ತ',
    minimumAdvance: 'ಕನಿಷ್ಠ ಮುಂಗಡ ಅಗತ್ಯ', selectMachineFirst: 'ಮೊದಲು ಯಂತ್ರ ಆಯ್ಕೆ ಮಾಡಿ',
    viewMachines: '→ ಯಂತ್ರಗಳು ನೋಡಿ', bookingConfirm: 'ಬುಕಿಂಗ್ ದೃಢೀಕರಿಸಿ',
    walletDeduct: 'ಮುಂಗಡ ವಾಲೆಟ್‌ನಿಂದ ಕಡಿತಗೊಳ್ಳುತ್ತದೆ · ನಗದು ಇಲ್ಲ · GST ಸ್ವಯಂಚಾಲಿತವಾಗಿ ರಚಿಸಲ್ಪಡುತ್ತದೆ',
    noBookings: 'ಸಕ್ರಿಯ ಬುಕಿಂಗ್‌ಗಳಿಲ್ಲ', goBook: '→ ಯಂತ್ರ ಬುಕ್ ಮಾಡಿ',
    completeBookings: 'ಪೂರ್ಣ ಬುಕಿಂಗ್‌ಗಳು', transactions: 'ವಹಿವಾಟು ಇತಿಹಾಸ',
    customAmount: 'ಕಸ್ಟಮ್ ಮೊತ್ತ (ಕನಿಷ್ಠ ₹5,000)', paymentMethods: 'ಪಾವತಿ ವಿಧಾನಗಳು',
    alertLog: 'ಎಚ್ಚರಿಕೆ ಲಾಗ್', sendWhatsapp: 'WhatsApp ನಲ್ಲಿ ಕಳುಹಿಸಿ',
    sendEmail: 'ಇಮೇಲ್ ಕಳುಹಿಸಿ', yourMessage: 'ನಿಮ್ಮ ಪ್ರಶ್ನೆ ಅಥವಾ ಸಮಸ್ಯೆ ಬರೆಯಿರಿ...',
    importantInfo: 'ಯಂತ್ರ ಮಾಲೀಕರಿಗೆ ಮುಖ್ಯ ಮಾಹಿತಿ',
    machineDetails: 'ಯಂತ್ರ & ಆಪರೇಟರ್ ವಿವರಗಳು',
    liveCamera: '360° ಲೈವ್ ಕ್ಯಾಮೆರಾ — ಬುಕಿಂಗ್ ನಂತರ',
    liveBookAvail: 'ಬುಕಿಂಗ್ ನಂತರ ಲೈವ್ ಫೀಡ್ ಲಭ್ಯ',
    rateCard: 'ದರ ಕಾರ್ಡ್ (ಆಪರೇಟರ್ ಸೇರಿ)', selectBook: 'ಈ ಯಂತ್ರ ಬುಕ್ ಮಾಡಿ →',
    selectCalc: '📋 ಆಯ್ಕೆ ಮಾಡಿ & ವೆಚ್ಚ ನೋಡಿ →',
    bookingType: 'ಬುಕಿಂಗ್ ವಿಧ ಆಯ್ಕೆ ಮಾಡಿ', selectQty: 'ಪ್ರಮಾಣ ಆಯ್ಕೆ ಮಾಡಿ',
    walletSufficient: '✅ ಮುಂದುವರಿಯಿರಿ', walletInsufficient: '❌ ಸಾಕಾಗದು',
    rechargeFirst: '⚡ ಮೊದಲು ವಾಲೆಟ್ ರೀಚಾರ್ಜ್ ಮಾಡಿ',
    cancelWarning: 'ನೀವು ರದ್ದು ಮಾಡಲು ಬಯಸುತ್ತೀರಾ?',
    noBankRefund: '❌ ಬ್ಯಾಂಕ್ ರಿಫಂಡ್ ಇಲ್ಲ — ವಾಲೆಟ್ ಕ್ರೆಡಿಟ್ ಮಾತ್ರ',
    walletCredit: 'ವಾಲೆಟ್ ಕ್ರೆಡಿಟ್', penaltyDeduct: 'ರದ್ದು ದಂಡ (1 ಗಂಟೆ)',
    blacklistWarning: '⛔ ಬ್ಲ್ಯಾಕ್‌ಲಿಸ್ಟ್ ಎಚ್ಚರಿಕೆ',
    directContactProhibited: 'ನೇರ ಸಂಪರ್ಕ ಕಟ್ಟುನಿಟ್ಟಾಗಿ ನಿಷೇಧಿಸಲಾಗಿದೆ',
    understood: '✅ ಅರ್ಥಮಾಡಿಕೊಂಡೆ — ವೇದಿಕೆ ಬಳಸುತ್ತೇನೆ',
    lockWarning: 'Teltonika GPS ಮೂಲಕ ಯಂತ್ರದ ಇಗ್ನಿಷನ್ ದೂರದಿಂದ ನಿಷ್ಕ್ರಿಯಗೊಳಿಸಲಾಗುತ್ತದೆ.',
    lockConfirm: '🔒 ಲಾಕ್ ದೃಢೀಕರಿಸಿ', allStats: 'ಸಂಪೂರ್ಣ ಅಂಕಿಅಂಶಗಳು',
    changeLanguage: 'ಭಾಷೆ ಬದಲಿಸಿ',
  },

  ml: {
    appName: 'ഡെവലപ്‌മെന്റ് എക്‌സ്‌പ്രസ്',
    tagline: 'അടിസ്ഥാന സൗകര്യത്തിന്റെ സ്വർണ്ണ നിലവാരം',
    platform: 'നിർമ്മാണ മാനേജ്‌മെന്റ് പ്ലാറ്റ്‌ഫോം',
    selectRole: 'റോൾ തിരഞ്ഞെടുക്കൂ',
    emailAddress: 'ഇമെയിൽ വിലാസം',
    password: 'പാസ്‌വേഡ്',
    signIn: 'സൈൻ ഇൻ ചെയ്യൂ',
    signingIn: 'ലോഗിൻ ആകുന്നു...',
    adminRole: 'അഡ്മിൻ — മാനേജിംഗ് ഡയറക്ടർ',
    ownerRole: 'മെഷീൻ ഉടമ',
    clientRole: 'ക്ലയന്റ് (കോൺട്രാക്ടർ)',
    operatorRole: 'ഓപ്പറേറ്റർ',
    since: '2011 മുതൽ · 15 വർഷത്തെ മികവ്',
    dashboard: 'ഡാഷ്‌ബോർഡ്', myMachines: 'എന്റെ മെഷീനുകൾ',
    register: 'മെഷീൻ രജിസ്ട്രേഷൻ', tracking: 'GPS ട്രാക്കിംഗ്',
    reports: 'റിപ്പോർട്ടുകൾ & പേയ്‌മെന്റ്', alerts: 'അലർട്ടുകൾ',
    support: 'പിന്തുണ', bookMachine: 'മെഷീൻ ബുക്ക് ചെയ്യൂ',
    costCalculator: 'ചെലവ് കാൽക്കുലേറ്റർ', myBookings: 'എന്റെ ബുക്കിംഗ്',
    liveTracking: 'തൽസമയ ട്രാക്കിംഗ്', wallet: 'വാലറ്റ് & പേയ്‌മെന്റ്',
    overview: 'അവലോകനം', machines: 'മെഷീനുകൾ', clients: 'ക്ലയന്റുകൾ',
    owners: 'ഉടമകൾ', operators: 'ഓപ്പറേറ്റർമാർ',
    billingWallet: 'വാലറ്റ് & ബില്ലിംഗ്', iot: 'IoT & GPS', logout: 'ലോഗ്ഔട്ട്',
    active: 'സജീവം', idle: 'നിഷ്‌ക്രിയം', available: 'ലഭ്യം', busy: 'തിരക്ക്',
    locked: 'ലോക്ക്', live: 'തൽസമയം', totalMachines: 'ആകെ മെഷീനുകൾ',
    activeToday: 'ഇന്ന് സജീവം', walletBalance: 'വാലറ്റ് ബാലൻസ്',
    activeBookings: 'സജീവ ബുക്കിംഗ്', recharge: 'റീചാർജ്',
    rechargeWallet: '+ വാലറ്റ് റീചാർജ്', payNow: 'ഇപ്പോൾ പേ ചെയ്യൂ',
    confirm: 'സ്ഥിരീകരിക്കൂ', cancel: 'റദ്ദാക്കൂ', back: 'തിരിച്ചു പോകൂ',
    download: 'ഡൗൺലോഡ്', submit: 'സമർപ്പിക്കൂ', save: 'സേവ് ചെയ്യൂ',
    perHour: 'മണിക്കൂറിന്', perDay: 'ദിവസത്തിന്', perWeek: 'ആഴ്ചയ്ക്ക്',
    perMonth: 'മാസത്തിന്', advance: 'അഡ്വാൻസ്', commission: 'കമ്മീഷൻ',
    netPayable: 'നെറ്റ് നൽകേണ്ടത്', grossBilling: 'മൊത്തം ബില്ലിംഗ്',
    bookNow: 'ഇപ്പോൾ ബുക്ക് ചെയ്യൂ', confirmBooking: 'ബുക്കിംഗ് സ്ഥിരീകരിക്കൂ',
    cancelBooking: 'ബുക്കിംഗ് റദ്ദാക്കൂ', machineStatus: 'മെഷീൻ സ്ഥിതി',
    fuelLevel: 'ഇന്ധന നില', condition: 'അവസ്ഥ', location: 'സ്ഥാനം',
    operator: 'ഓപ്പറേറ്റർ', experience: 'പരിചയം', rating: 'റേറ്റിംഗ്',
    hours: 'മണിക്കൂർ', days: 'ദിവസം', weeks: 'ആഴ്ചകൾ', months: 'മാസങ്ങൾ',
    gstInvoice: 'GST ഇൻവോയ്സ്', bookingHistory: 'ബുക്കിംഗ് ചരിത്രം',
    paymentHistory: 'പേയ്‌മെന്റ് ചരിത്രം', noAlerts: 'അലർട്ടുകൾ ഇല്ല!',
    allMachinesOk: 'എല്ലാ മെഷീനുകളും ശരിയായി പ്രവർത്തിക്കുന്നു.',
    lockMachine: 'മെഷീൻ ലോക്ക് ചെയ്യൂ', machineReg: 'മെഷീൻ രജിസ്ട്രേഷൻ ഫോം',
    ownerInfo: 'ഉടമ വിവരങ്ങൾ', machineInfo: 'മെഷീൻ വിവരങ്ങൾ',
    pdiInfo: 'PDI പരിശോധന', documents: 'രേഖകൾ അപ്‌ലോഡ്',
    agreement: 'നിബന്ധനകൾ & കരാർ', selectFile: 'ഫയൽ തിരഞ്ഞെടുക്കൂ',
    walletOnly: 'വാലറ്റ് മാത്രം · പണം സ്വീകരിക്കില്ല',
    noRefund: 'റീഫണ്ട് ഇല്ല നയം', cancelPolicy: 'റദ്ദാക്കൽ നയം',
    whatsapp: 'WhatsApp', email: 'ഇമെയിൽ പിന്തുണ', send: 'അയയ്ക്കൂ',
    year: 'വർഷം', total: 'ആകെ', tax: 'നികുതി', status: 'സ്ഥിതി',
    type: 'തരം', date: 'തീയതി', machine: 'മെഷീൻ', client: 'ക്ലയന്റ്',
    hmrToday: 'ഇന്നത്തെ HMR', hmrTotal: 'ആകെ HMR', earnings: 'വരുമാനം',
    amount: 'തുക', ref: 'റഫറൻസ് നം.', fuel: 'ഇന്ധനം', ignition: 'ഇഗ്നിഷൻ',
    speed: 'വേഗത', completedBookings: 'പൂർത്തിയായ ബുക്കിംഗ്',
    instantCost: 'തൽക്ഷണ ചെലവ് കാൽക്കുലേറ്റർ', baseAmount: 'അടിസ്ഥാന തുക',
    gst18: 'GST (18%)', grandTotal: 'മൊത്തം തുക',
    minimumAdvance: 'ഏറ്റവും കുറഞ്ഞ അഡ്വാൻസ് ആവശ്യം',
    selectMachineFirst: 'ആദ്യം മെഷീൻ തിരഞ്ഞെടുക്കൂ',
    viewMachines: '→ മെഷീനുകൾ കാണൂ', bookingConfirm: 'ബുക്കിംഗ് സ്ഥിരീകരിക്കൂ',
    walletDeduct: 'അഡ്വാൻസ് വാലറ്റിൽ നിന്ന് കുറയ്ക്കും · പണം ഇല്ല · GST സ്വയം സൃഷ്ടിക്കും',
    noBookings: 'സജീവ ബുക്കിംഗ് ഇല്ല', goBook: '→ മെഷീൻ ബുക്ക് ചെയ്യൂ',
    completeBookings: 'പൂർത്തിയായ ബുക്കിംഗ്', transactions: 'ഇടപാട് ചരിത്രം',
    customAmount: 'ഇഷ്ടാനുസൃത തുക (കുറഞ്ഞത് ₹5,000)',
    paymentMethods: 'പേയ്‌മെന്റ് രീതികൾ', alertLog: 'അലർട്ട് ലോഗ്',
    sendWhatsapp: 'WhatsApp-ൽ അയയ്ക്കൂ', sendEmail: 'ഇമെയിൽ അയയ്ക്കൂ',
    yourMessage: 'നിങ്ങളുടെ ചോദ്യം അല്ലെങ്കിൽ പ്രശ്നം എഴുതൂ...',
    importantInfo: 'മെഷീൻ ഉടമകൾക്ക് പ്രധാന വിവരം',
    machineDetails: 'മെഷീൻ & ഓപ്പറേറ്റർ വിശദാംശങ്ങൾ',
    liveCamera: '360° തൽസമയ ക്യാമറ — ബുക്കിംഗ് ശേഷം',
    liveBookAvail: 'ബുക്കിംഗ് ശേഷം തൽസമയ ഫീഡ് ലഭ്യം',
    rateCard: 'നിരക്ക് കാർഡ് (ഓപ്പറേറ്റർ ഉൾപ്പെടെ)',
    selectBook: 'ഈ മെഷീൻ ബുക്ക് ചെയ്യൂ →',
    selectCalc: '📋 തിരഞ്ഞെടുക്കൂ & ചെലവ് കാണൂ →',
    bookingType: 'ബുക്കിംഗ് തരം തിരഞ്ഞെടുക്കൂ',
    selectQty: 'അളവ് തിരഞ്ഞെടുക്കൂ',
    walletSufficient: '✅ തുടരൂ', walletInsufficient: '❌ അപര്യാപ്തം',
    rechargeFirst: '⚡ ആദ്യം വാലറ്റ് റീചാർജ് ചെയ്യൂ',
    cancelWarning: 'നിങ്ങൾ റദ്ദാക്കണമോ?',
    noBankRefund: '❌ ബാങ്ക് റീഫണ്ട് ഇല്ല — വാലറ്റ് ക്രെഡിറ്റ് മാത്രം',
    walletCredit: 'വാലറ്റ് ക്രെഡിറ്റ്', penaltyDeduct: 'റദ്ദാക്കൽ പിഴ (1 മണിക്കൂർ)',
    blacklistWarning: '⛔ ബ്ലാക്ക്‌ലിസ്റ്റ് മുന്നറിയിപ്പ്',
    directContactProhibited: 'നേരിട്ടുള്ള ബന്ധപ്പെടൽ കർശനമായി നിരോധിച്ചിരിക്കുന്നു',
    understood: '✅ മനസ്സിലായി — പ്ലാറ്റ്‌ഫോം ഉപയോഗിക്കും',
    lockWarning: 'Teltonika GPS വഴി മെഷീൻ ഇഗ്നിഷൻ വിദൂരമായി പ്രവർത്തനരഹിതമാക്കും.',
    lockConfirm: '🔒 ലോക്ക് സ്ഥിരീകരിക്കൂ', allStats: 'പൂർണ്ണ കണക്കുകൾ',
    changeLanguage: 'ഭാഷ മാറ്റൂ',
  },

  pa: {
    appName: 'ਡਿਵੈਲਪਮੈਂਟ ਐਕਸਪ੍ਰੈਸ',
    tagline: 'ਬੁਨਿਆਦੀ ਢਾਂਚੇ ਦਾ ਸੋਨੇ ਦਾ ਮਿਆਰ',
    platform: 'ਨਿਰਮਾਣ ਪ੍ਰਬੰਧਨ ਪਲੇਟਫਾਰਮ',
    selectRole: 'ਭੂਮਿਕਾ ਚੁਣੋ',
    emailAddress: 'ਈਮੇਲ ਪਤਾ',
    password: 'ਪਾਸਵਰਡ',
    signIn: 'ਸਾਈਨ ਇਨ ਕਰੋ',
    signingIn: 'ਲੌਗਿਨ ਹੋ ਰਿਹਾ ਹੈ...',
    adminRole: 'ਐਡਮਿਨ — ਪ੍ਰਬੰਧਕੀ ਨਿਰਦੇਸ਼ਕ',
    ownerRole: 'ਮਸ਼ੀਨ ਮਾਲਕ',
    clientRole: 'ਕਲਾਇੰਟ (ਠੇਕੇਦਾਰ)',
    operatorRole: 'ਆਪਰੇਟਰ',
    since: '2011 ਤੋਂ · 15 ਸਾਲਾਂ ਦੀ ਉੱਤਮਤਾ',
    dashboard: 'ਡੈਸ਼ਬੋਰਡ', myMachines: 'ਮੇਰੀਆਂ ਮਸ਼ੀਨਾਂ',
    register: 'ਮਸ਼ੀਨ ਰਜਿਸਟ੍ਰੇਸ਼ਨ', tracking: 'GPS ਟਰੈਕਿੰਗ',
    reports: 'ਰਿਪੋਰਟਾਂ & ਭੁਗਤਾਨ', alerts: 'ਚੇਤਾਵਨੀਆਂ',
    support: 'ਸਹਾਇਤਾ', bookMachine: 'ਮਸ਼ੀਨ ਬੁੱਕ ਕਰੋ',
    costCalculator: 'ਲਾਗਤ ਕੈਲਕੁਲੇਟਰ', myBookings: 'ਮੇਰੀਆਂ ਬੁਕਿੰਗਾਂ',
    liveTracking: 'ਲਾਈਵ ਟਰੈਕਿੰਗ', wallet: 'ਵਾਲੇਟ & ਭੁਗਤਾਨ',
    overview: 'ਸੰਖੇਪ ਜਾਣਕਾਰੀ', machines: 'ਮਸ਼ੀਨਾਂ', clients: 'ਗਾਹਕ',
    owners: 'ਮਾਲਕ', operators: 'ਆਪਰੇਟਰ',
    billingWallet: 'ਵਾਲੇਟ & ਬਿਲਿੰਗ', iot: 'IoT & GPS', logout: 'ਲੌਗਆਉਟ',
    active: 'ਸਰਗਰਮ', idle: 'ਅਕਿਰਿਆਸ਼ੀਲ', available: 'ਉਪਲਬਧ', busy: 'ਰੁੱਝਿਆ',
    locked: 'ਲੌਕ', live: 'ਲਾਈਵ', totalMachines: 'ਕੁੱਲ ਮਸ਼ੀਨਾਂ',
    activeToday: 'ਅੱਜ ਸਰਗਰਮ', walletBalance: 'ਵਾਲੇਟ ਬੈਲੈਂਸ',
    activeBookings: 'ਸਰਗਰਮ ਬੁਕਿੰਗਾਂ', recharge: 'ਰੀਚਾਰਜ',
    rechargeWallet: '+ ਵਾਲੇਟ ਰੀਚਾਰਜ', payNow: 'ਹੁਣ ਭੁਗਤਾਨ ਕਰੋ',
    confirm: 'ਪੁਸ਼ਟੀ ਕਰੋ', cancel: 'ਰੱਦ ਕਰੋ', back: 'ਵਾਪਸ ਜਾਓ',
    download: 'ਡਾਊਨਲੋਡ', submit: 'ਜਮ੍ਹਾਂ ਕਰੋ', save: 'ਸੇਵ ਕਰੋ',
    perHour: 'ਪ੍ਰਤੀ ਘੰਟਾ', perDay: 'ਪ੍ਰਤੀ ਦਿਨ', perWeek: 'ਪ੍ਰਤੀ ਹਫ਼ਤਾ',
    perMonth: 'ਪ੍ਰਤੀ ਮਹੀਨਾ', advance: 'ਅਡਵਾਂਸ', commission: 'ਕਮਿਸ਼ਨ',
    netPayable: 'ਸ਼ੁੱਧ ਦੇਣਯੋਗ', grossBilling: 'ਕੁੱਲ ਬਿਲਿੰਗ',
    bookNow: 'ਹੁਣੇ ਬੁੱਕ ਕਰੋ', confirmBooking: 'ਬੁਕਿੰਗ ਪੁਸ਼ਟੀ ਕਰੋ',
    cancelBooking: 'ਬੁਕਿੰਗ ਰੱਦ ਕਰੋ', machineStatus: 'ਮਸ਼ੀਨ ਸਥਿਤੀ',
    fuelLevel: 'ਬਾਲਣ ਪੱਧਰ', condition: 'ਸਥਿਤੀ', location: 'ਸਥਾਨ',
    operator: 'ਆਪਰੇਟਰ', experience: 'ਤਜਰਬਾ', rating: 'ਰੇਟਿੰਗ',
    hours: 'ਘੰਟੇ', days: 'ਦਿਨ', weeks: 'ਹਫ਼ਤੇ', months: 'ਮਹੀਨੇ',
    gstInvoice: 'GST ਇਨਵੌਇਸ', bookingHistory: 'ਬੁਕਿੰਗ ਇਤਿਹਾਸ',
    paymentHistory: 'ਭੁਗਤਾਨ ਇਤਿਹਾਸ', noAlerts: 'ਕੋਈ ਚੇਤਾਵਨੀ ਨਹੀਂ!',
    allMachinesOk: 'ਸਾਰੀਆਂ ਮਸ਼ੀਨਾਂ ਠੀਕ ਚੱਲ ਰਹੀਆਂ ਹਨ।',
    lockMachine: 'ਮਸ਼ੀਨ ਲੌਕ ਕਰੋ', machineReg: 'ਮਸ਼ੀਨ ਰਜਿਸਟ੍ਰੇਸ਼ਨ ਫਾਰਮ',
    ownerInfo: 'ਮਾਲਕ ਦੀ ਜਾਣਕਾਰੀ', machineInfo: 'ਮਸ਼ੀਨ ਦੀ ਜਾਣਕਾਰੀ',
    pdiInfo: 'PDI ਜਾਂਚ', documents: 'ਦਸਤਾਵੇਜ਼ ਅਪਲੋਡ',
    agreement: 'ਸ਼ਰਤਾਂ & ਸਮਝੌਤਾ', selectFile: 'ਫਾਈਲ ਚੁਣੋ',
    walletOnly: 'ਸਿਰਫ਼ ਵਾਲੇਟ · ਨਕਦ ਸਵੀਕਾਰ ਨਹੀਂ',
    noRefund: 'ਰਿਫੰਡ ਨਹੀਂ ਨੀਤੀ', cancelPolicy: 'ਰੱਦ ਕਰਨ ਦੀ ਨੀਤੀ',
    whatsapp: 'WhatsApp', email: 'ਈਮੇਲ ਸਹਾਇਤਾ', send: 'ਭੇਜੋ',
    year: 'ਸਾਲ', total: 'ਕੁੱਲ', tax: 'ਟੈਕਸ', status: 'ਸਥਿਤੀ',
    type: 'ਕਿਸਮ', date: 'ਮਿਤੀ', machine: 'ਮਸ਼ੀਨ', client: 'ਗਾਹਕ',
    hmrToday: 'ਅੱਜ ਦਾ HMR', hmrTotal: 'ਕੁੱਲ HMR', earnings: 'ਕਮਾਈ',
    amount: 'ਰਾਸ਼ੀ', ref: 'ਹਵਾਲਾ ਨੰ.', fuel: 'ਬਾਲਣ', ignition: 'ਇਗਨੀਸ਼ਨ',
    speed: 'ਗਤੀ', completedBookings: 'ਪੂਰੀਆਂ ਬੁਕਿੰਗਾਂ',
    instantCost: 'ਤੁਰੰਤ ਲਾਗਤ ਕੈਲਕੁਲੇਟਰ', baseAmount: 'ਅਧਾਰ ਰਾਸ਼ੀ',
    gst18: 'GST (18%)', grandTotal: 'ਕੁੱਲ ਜੋੜ',
    minimumAdvance: 'ਘੱਟੋ-ਘੱਟ ਅਡਵਾਂਸ ਲੋੜੀਂਦਾ',
    selectMachineFirst: 'ਪਹਿਲਾਂ ਮਸ਼ੀਨ ਚੁਣੋ', viewMachines: '→ ਮਸ਼ੀਨਾਂ ਦੇਖੋ',
    bookingConfirm: 'ਬੁਕਿੰਗ ਪੁਸ਼ਟੀ ਕਰੋ',
    walletDeduct: 'ਅਡਵਾਂਸ ਵਾਲੇਟ ਤੋਂ ਕੱਟਿਆ ਜਾਵੇਗਾ · ਨਕਦ ਨਹੀਂ · GST ਆਟੋ ਬਣੇਗਾ',
    noBookings: 'ਕੋਈ ਸਰਗਰਮ ਬੁਕਿੰਗ ਨਹੀਂ', goBook: '→ ਮਸ਼ੀਨ ਬੁੱਕ ਕਰੋ',
    completeBookings: 'ਪੂਰੀਆਂ ਬੁਕਿੰਗਾਂ', transactions: 'ਲੈਣ-ਦੇਣ ਇਤਿਹਾਸ',
    customAmount: 'ਕਸਟਮ ਰਾਸ਼ੀ (ਘੱਟੋ-ਘੱਟ ₹5,000)',
    paymentMethods: 'ਭੁਗਤਾਨ ਦੇ ਤਰੀਕੇ', alertLog: 'ਚੇਤਾਵਨੀ ਲੌਗ',
    sendWhatsapp: 'WhatsApp ਤੇ ਭੇਜੋ', sendEmail: 'ਈਮੇਲ ਭੇਜੋ',
    yourMessage: 'ਆਪਣਾ ਸਵਾਲ ਜਾਂ ਸਮੱਸਿਆ ਲਿਖੋ...',
    importantInfo: 'ਮਸ਼ੀਨ ਮਾਲਕਾਂ ਲਈ ਮਹੱਤਵਪੂਰਨ ਜਾਣਕਾਰੀ',
    machineDetails: 'ਮਸ਼ੀਨ & ਆਪਰੇਟਰ ਵੇਰਵੇ',
    liveCamera: '360° ਲਾਈਵ ਕੈਮਰਾ — ਬੁਕਿੰਗ ਤੋਂ ਬਾਅਦ',
    liveBookAvail: 'ਬੁਕਿੰਗ ਤੋਂ ਬਾਅਦ ਲਾਈਵ ਫੀਡ ਉਪਲਬਧ',
    rateCard: 'ਦਰ ਕਾਰਡ (ਆਪਰੇਟਰ ਸਮੇਤ)',
    selectBook: 'ਇਹ ਮਸ਼ੀਨ ਬੁੱਕ ਕਰੋ →',
    selectCalc: '📋 ਚੁਣੋ & ਲਾਗਤ ਦੇਖੋ →',
    bookingType: 'ਬੁਕਿੰਗ ਕਿਸਮ ਚੁਣੋ', selectQty: 'ਮਾਤਰਾ ਚੁਣੋ',
    walletSufficient: '✅ ਅੱਗੇ ਵਧੋ', walletInsufficient: '❌ ਨਾਕਾਫ਼ੀ',
    rechargeFirst: '⚡ ਪਹਿਲਾਂ ਵਾਲੇਟ ਰੀਚਾਰਜ ਕਰੋ',
    cancelWarning: 'ਕੀ ਤੁਸੀਂ ਰੱਦ ਕਰਨਾ ਚਾਹੁੰਦੇ ਹੋ?',
    noBankRefund: '❌ ਬੈਂਕ ਰਿਫੰਡ ਨਹੀਂ — ਸਿਰਫ਼ ਵਾਲੇਟ ਕ੍ਰੈਡਿਟ',
    walletCredit: 'ਵਾਲੇਟ ਕ੍ਰੈਡਿਟ', penaltyDeduct: 'ਰੱਦ ਕਰਨ ਦਾ ਜੁਰਮਾਨਾ (1 ਘੰਟਾ)',
    blacklistWarning: '⛔ ਬਲੈਕਲਿਸਟ ਚੇਤਾਵਨੀ',
    directContactProhibited: 'ਸਿੱਧਾ ਸੰਪਰਕ ਸਖ਼ਤੀ ਨਾਲ ਵਰਜਿਤ',
    understood: '✅ ਸਮਝ ਗਿਆ — ਪਲੇਟਫਾਰਮ ਵਰਤਾਂਗਾ',
    lockWarning: 'Teltonika GPS ਰਾਹੀਂ ਮਸ਼ੀਨ ਦਾ ਇਗਨੀਸ਼ਨ ਦੂਰੋਂ ਬੰਦ ਕੀਤਾ ਜਾਵੇਗਾ।',
    lockConfirm: '🔒 ਲੌਕ ਪੁਸ਼ਟੀ ਕਰੋ', allStats: 'ਪੂਰੇ ਅੰਕੜੇ',
    changeLanguage: 'ਭਾਸ਼ਾ ਬਦਲੋ',
  },

  bn: {
    appName: 'ডেভেলপমেন্ট এক্সপ্রেস',
    tagline: 'অবকাঠামোর স্বর্ণ মান',
    platform: 'নির্মাণ ব্যবস্থাপনা প্ল্যাটফর্ম',
    selectRole: 'ভূমিকা নির্বাচন করুন',
    emailAddress: 'ইমেইল ঠিকানা',
    password: 'পাসওয়ার্ড',
    signIn: 'সাইন ইন করুন',
    signingIn: 'লগইন হচ্ছে...',
    adminRole: 'অ্যাডমিন — ব্যবস্থাপনা পরিচালক',
    ownerRole: 'মেশিন মালিক',
    clientRole: 'ক্লায়েন্ট (ঠিকাদার)',
    operatorRole: 'অপারেটর',
    since: '২০১১ থেকে · ১৫ বছরের শ্রেষ্ঠত্ব',
    dashboard: 'ড্যাশবোর্ড', myMachines: 'আমার মেশিন',
    register: 'মেশিন নিবন্ধন', tracking: 'GPS ট্র্যাকিং',
    reports: 'রিপোর্ট ও পেমেন্ট', alerts: 'সতর্কতা',
    support: 'সহায়তা', bookMachine: 'মেশিন বুক করুন',
    costCalculator: 'খরচ ক্যালকুলেটর', myBookings: 'আমার বুকিং',
    liveTracking: 'লাইভ ট্র্যাকিং', wallet: 'ওয়ালেট ও পেমেন্ট',
    overview: 'পর্যালোচনা', machines: 'মেশিন', clients: 'ক্লায়েন্ট',
    owners: 'মালিক', operators: 'অপারেটর',
    billingWallet: 'ওয়ালেট ও বিলিং', iot: 'IoT ও GPS', logout: 'লগআউট',
    active: 'সক্রিয়', idle: 'নিষ্ক্রিয়', available: 'উপলব্ধ', busy: 'ব্যস্ত',
    locked: 'লক', live: 'লাইভ', totalMachines: 'মোট মেশিন',
    activeToday: 'আজ সক্রিয়', walletBalance: 'ওয়ালেট ব্যালেন্স',
    activeBookings: 'সক্রিয় বুকিং', recharge: 'রিচার্জ',
    rechargeWallet: '+ ওয়ালেট রিচার্জ', payNow: 'এখন পেমেন্ট করুন',
    confirm: 'নিশ্চিত করুন', cancel: 'বাতিল করুন', back: 'পিছনে যান',
    download: 'ডাউনলোড', submit: 'জমা দিন', save: 'সংরক্ষণ করুন',
    perHour: 'প্রতি ঘন্টা', perDay: 'প্রতি দিন', perWeek: 'প্রতি সপ্তাহ',
    perMonth: 'প্রতি মাস', advance: 'অগ্রিম', commission: 'কমিশন',
    netPayable: 'নিট পরিশোধযোগ্য', grossBilling: 'মোট বিলিং',
    bookNow: 'এখনই বুক করুন', confirmBooking: 'বুকিং নিশ্চিত করুন',
    cancelBooking: 'বুকিং বাতিল করুন', machineStatus: 'মেশিন অবস্থা',
    fuelLevel: 'জ্বালানি স্তর', condition: 'অবস্থা', location: 'অবস্থান',
    operator: 'অপারেটর', experience: 'অভিজ্ঞতা', rating: 'রেটিং',
    hours: 'ঘন্টা', days: 'দিন', weeks: 'সপ্তাহ', months: 'মাস',
    gstInvoice: 'GST ইনভয়েস', bookingHistory: 'বুকিং ইতিহাস',
    paymentHistory: 'পেমেন্ট ইতিহাস', noAlerts: 'কোনো সতর্কতা নেই!',
    allMachinesOk: 'সব মেশিন ঠিকমতো চলছে।',
    lockMachine: 'মেশিন লক করুন', machineReg: 'মেশিন নিবন্ধন ফর্ম',
    ownerInfo: 'মালিকের তথ্য', machineInfo: 'মেশিনের তথ্য',
    pdiInfo: 'PDI পরিদর্শন', documents: 'নথি আপলোড',
    agreement: 'শর্তাবলী ও চুক্তি', selectFile: 'ফাইল নির্বাচন করুন',
    walletOnly: 'শুধুমাত্র ওয়ালেট · নগদ গ্রহণযোগ্য নয়',
    noRefund: 'নো রিফান্ড নীতি', cancelPolicy: 'বাতিলকরণ নীতি',
    whatsapp: 'WhatsApp', email: 'ইমেইল সহায়তা', send: 'পাঠান',
    year: 'বছর', total: 'মোট', tax: 'কর', status: 'অবস্থা',
    type: 'ধরন', date: 'তারিখ', machine: 'মেশিন', client: 'ক্লায়েন্ট',
    hmrToday: 'আজকের HMR', hmrTotal: 'মোট HMR', earnings: 'আয়',
    amount: 'পরিমাণ', ref: 'রেফারেন্স নং', fuel: 'জ্বালানি',
    ignition: 'ইগনিশন', speed: 'গতি', completedBookings: 'সম্পন্ন বুকিং',
    instantCost: 'তাৎক্ষণিক খরচ ক্যালকুলেটর', baseAmount: 'মূল পরিমাণ',
    gst18: 'GST (18%)', grandTotal: 'মোট যোগফল',
    minimumAdvance: 'ন্যূনতম অগ্রিম প্রয়োজন',
    selectMachineFirst: 'প্রথমে মেশিন নির্বাচন করুন',
    viewMachines: '→ মেশিন দেখুন', bookingConfirm: 'বুকিং নিশ্চিত করুন',
    walletDeduct: 'অগ্রিম ওয়ালেট থেকে কাটা হবে · নগদ নয় · GST স্বয়ংক্রিয় তৈরি হবে',
    noBookings: 'সক্রিয় বুকিং নেই', goBook: '→ মেশিন বুক করুন',
    completeBookings: 'সম্পন্ন বুকিং', transactions: 'লেনদেন ইতিহাস',
    customAmount: 'কাস্টম পরিমাণ (ন্যূনতম ₹5,000)',
    paymentMethods: 'পেমেন্ট পদ্ধতি', alertLog: 'সতর্কতা লগ',
    sendWhatsapp: 'WhatsApp-এ পাঠান', sendEmail: 'ইমেইল পাঠান',
    yourMessage: 'আপনার প্রশ্ন বা সমস্যা লিখুন...',
    importantInfo: 'মেশিন মালিকদের জন্য গুরুত্বপূর্ণ তথ্য',
    machineDetails: 'মেশিন ও অপারেটর বিবরণ',
    liveCamera: '360° লাইভ ক্যামেরা — বুকিংয়ের পরে',
    liveBookAvail: 'বুকিংয়ের পরে লাইভ ফিড পাওয়া যাবে',
    rateCard: 'রেট কার্ড (অপারেটর সহ)', selectBook: 'এই মেশিন বুক করুন →',
    selectCalc: '📋 নির্বাচন করুন ও খরচ দেখুন →',
    bookingType: 'বুকিং ধরন নির্বাচন করুন', selectQty: 'পরিমাণ নির্বাচন করুন',
    walletSufficient: '✅ এগিয়ে যান', walletInsufficient: '❌ অপর্যাপ্ত',
    rechargeFirst: '⚡ প্রথমে ওয়ালেট রিচার্জ করুন',
    cancelWarning: 'আপনি কি বাতিল করতে চান?',
    noBankRefund: '❌ ব্যাংক রিফান্ড নেই — শুধু ওয়ালেট ক্রেডিট',
    walletCredit: 'ওয়ালেট ক্রেডিট', penaltyDeduct: 'বাতিলকরণ জরিমানা (১ ঘন্টা)',
    blacklistWarning: '⛔ ব্ল্যাকলিস্ট সতর্কতা',
    directContactProhibited: 'সরাসরি যোগাযোগ কঠোরভাবে নিষিদ্ধ',
    understood: '✅ বুঝেছি — প্ল্যাটফর্ম ব্যবহার করব',
    lockWarning: 'Teltonika GPS-এর মাধ্যমে মেশিনের ইগনিশন দূরবর্তীভাবে নিষ্ক্রিয় করা হবে।',
    lockConfirm: '🔒 লক নিশ্চিত করুন', allStats: 'সম্পূর্ণ পরিসংখ্যান',
    changeLanguage: 'ভাষা পরিবর্তন করুন',
  },
};

// Fallback: remaining languages use Hindi translations with native script
['or', 'as', 'ur', 'ne', 'kok', 'sat', 'mai', 'doi', 'bho', 'raj', 'cg', 'har'].forEach(code => {
  TRANSLATIONS[code] = { ...TRANSLATIONS['hi'] };
});

// Override specific keys for remaining languages
TRANSLATIONS['ur'] = {
  ...TRANSLATIONS['hi'],
  appName: 'ڈیولپمنٹ ایکسپریس',
  tagline: 'بنیادی ڈھانچے کا سنہری معیار',
  platform: 'تعمیرات مینجمنٹ پلیٹ فارم',
  selectRole: 'کردار منتخب کریں',
  emailAddress: 'ای میل پتہ',
  password: 'پاس ورڈ',
  signIn: 'سائن ان کریں',
  logout: 'لاگ آؤٹ',
  changeLanguage: 'زبان تبدیل کریں',
};

const LanguageContext = createContext();

export const LanguageProvider = ({ children }) => {
  const [lang, setLang] = useState('en');
  const t = (key) => TRANSLATIONS[lang]?.[key] || TRANSLATIONS['en'][key] || key;
  return (
    <LanguageContext.Provider value={{ lang, setLang, t, LANGUAGES }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => useContext(LanguageContext);
export default LanguageContext;